### ISSUE TITLE
packages that contain PC scripts

### ISSUE THREAD

**Issue by raisjn** [matteodelabre/toltec#224]
talked a little about this idea with eeems:

many remarkable packages are actually pieces of computer software that aren't run on the tablet. for simple enough software, it would be cool if you could plug in your rM tablet and use the software from it (for example: a bash or python script can be run on the host PC but installed on rM)

example ways this could work:

* install restream-pc package
* install a package that turns the rM into a hard drive or a package that sets up a webserver
* PC hits the web URL or mounts the rM's HD with the installed scripts (this mount would *only* contain PC relevant files and no other files from the rM)

**Comment by danshick** [comment]
It's a neat idea, but we should think about architecture and operating system differences as well as computer side dependencies. Restream, for example, requires ffmpeg/ffplay, lz4, ssh, and a POSIX environment.

Also, this makes toltec a more interesting target for malware. Probably not a huge concern as the PR process requires review, but we should watch for apps that have binary components, apps that download files, etc.

**Comment by matteodelabre** [comment]
I share your opinion that having to install things both on the rM and on a PC can be confusing to some users. However, I’m not convinced that this is the best way to solve the problem.

As @danshick mentioned, this would mean that we need to take differences between host systems into account, which would broaden this repo’s scope from supporting a specific embedded system to supporting a whole array of existing systems. We also need to consider that storage is quite scarce on the device.

Another way this could be solved is with a program running on the host system and able to both manage packages on the reMarkable via SSH and install the needed scripts on the host system itself. With this solution, the system differences are handled by this program which is external to the Toltec repo. Maybe this could be handled as part of @Eeems’ Toltec installer? (Not sure if managing opkg packages is in scope for that project.)

**Comment by Eeems** [comment]
Managing packages isn't currently in scope of the installer, but it doesn't have to remain out of scope.

**Comment by LinusCDE** [comment]
How about having a package that runs a webserver on the reMarkable?

Like having a package that just shows some "cards" for packages it recognized and are on device with some links.

The package could have the file defining what packages can provide what information on the website in the recipe directory and thus provide a way of other packages editing that.

Quick mockup on how a website might look like:
![grafik](https://user-images.githubusercontent.com/22298664/106298565-518e7e80-6254-11eb-9205-24ba3a6aadbe.png)

A file like `packages/hostinfoserverwhatever/package_info.yml`:

```yml:
restream: # name of the ipkg package
    display_name: reStream
    description: >-
        In order to stream the framebuffer to your PC, you need the following: ....
        More at: ...

rmservewacominput:
    display_name: rmServeWacomInput
    description: >-
        After you started the script on your reMarkable, use the following script to receive that data on your PC: ...
        More at: ...
```

This is just a suggestion. I don't intend to do anything in that aspect myself, but having such an info site that has this info might be a nice compromise between maintainability and simplicity.
